# errors

> 실행 실패의 종류들

## ZerodivisionError

> 0으로 나눈 경우
>
> ```
> print(3/0) 
> ```
>​	  `ZeroDivisionError: division by zero`

## TypeError

> 문자형과 정수형을 더한경우
>
> ex) 
> ```
> print('나는'+ 1994+'에 태어남')
>```
> ​	  `TypeError: can only concatenate str (not "int") to str`

## NameError

> 정의한것을 찾을 수 없을때
>
> ex) 
> ```
> print(x)
>```
> ​	  `NameError: name 'x' is not defined`

## ValueError

> 잘못된 형태를 입력받았을때
>
> ex)
>
> ```
> 	b=10
> 	print('%d%'% b)
> ```
> `ValueError: incomplete format`
## SyntaxError

> 문법적인 오류가 날때
>
> ```
> if b>10
>   print('합격')
> ```
> `SyntaxError: expected ':'`

## IndexError

> 범위를 벗어날때
>
> ```
>  a=[1,2,3,4]
>  print(a[4])
> ```
> `IndexError: list index out of range`

## UnboundLocalError

> 지역변수에 대한에러
>
> ```
> def add():
>     a = a+1
> add()
> ```
> `UnboundLocalError: local variable 'a' referenced before assignment`

## ModuleNotFoundError
> 찾는 모듈이 없을때
> ``` 
> import mymodule
> ```
>
> `ModuleNotFoundError: No module named 'mymodule'`
## FileNotFoundError
> 찾는 파일이 없을때
>
> ```
>  f = open('찾는파일.txt','r')
>  data = f.read()
>  f.close()
> ```
> `FileNotFoundError: [Errno 2] No such file or directory: '찾는파일.txt'`

## OSError

> 조건이 올바르지 않을때
>
> ```
>  f = open('c:\test.txt','r')
>  f.close()
> ```
> `OSError: [Errno 22] Invalid argument: 'c:\test.txt'`

